"""water_quality real

Revision ID: 99d594e40a9b
Revises: b4a09e1d207a
Create Date: 2024-12-27 05:35:46.565060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d594e40a9b'
down_revision: Union[str, None] = 'b4a09e1d207a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_quality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('do', sa.Float(), nullable=True),
    sa.Column('conductivity', sa.Float(), nullable=True),
    sa.Column('n_no2', sa.Float(), nullable=True),
    sa.Column('n_nh4', sa.Float(), nullable=True),
    sa.Column('p_po4', sa.Float(), nullable=True),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('cod', sa.Float(), nullable=True),
    sa.Column('aeromonas_total', sa.Float(), nullable=True),
    sa.Column('actual_wqi', sa.Float(), nullable=True),
    sa.Column('predicted_wqi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_quality')
    # ### end Alembic commands ###
